#pragma once

std::map<int64_t, std::string> parserDict = {
    { CHAR,         "CHAR"},
    { DECNUM,       "DECNUM"},
    { OCTNUM,       "OCTNUM"},
    { HEXNUM,       "HEXNUM"},
    { BINNUM,       "BINNUM"},
    { BYTE,         "BYTE"},
    { WORD,         "WORD"},
    { PLUS,         "PLUS"},
    { MINUS,        "MINUS"},
    { COMMA,        "COMMA"},
    { COLAN,        "COLAN"},
    { X,            "X"},
    { Y,            "Y"},
    { A,            "A"},
    { POUND,        "POUND"},
    { MUL,          "MUL"},
    { TEXT,         "TEXT"},
    { MOD,          "MOD"},
    { DIV,          "DIV"},
    { BIT_AND,      "BIT_AND"},
    { BIT_OR,       "BIT_OR"},
    { LOGICAL_AND,  "LOGICAL_AND"},
    { LOGICAL_OR,   "LOGICAL_OR"},
    { BIT_XOR,      "BIT_XOR"},
    { SLEFT,        "SHIFT_LEFT"},
    { SRIGHT,       "SHIFT_LEFT" },
    { LPAREN,       "LEFT_PAREN"},
    { RPAREN,       "RIGHT_PAREN"},
    { ONESCOMP,     "ONES_COMP"},
    { AT,           "AT" },
    { SYM,          "SYM" },
    { LOCALSYM,     "LOCAL_SYM" },
    { COMMENT,      "COMMENT" },
    { EQUAL,        "EQUALS" },
    { ORG,          "ORG" },
    { EOL,          "EOL" },
    { MACRO_DIR,    "MACRO_DEF" },
    { ENDMACRO_DIR, "END_MACRO" },
    { MACRO_PARAM,  "MACRO_PARAM" },
    { INCLUDE,      "INCLUDE"},
    { ORA,      "ORA"  },
    { AND,      "AND"  },
    { EOR,      "EOR"  },
    { ADC,      "ADC"  },
    { SBC,      "SBC"  },
    { CMP,      "CMP"  },
    { CPX,      "CPX"  },
    { CPY,      "CPY"  },
    { DEC,      "DEC"  },
    { DEX,      "DEX"  },
    { DEY,      "DEY"  },
    { INC,      "INC"  },
    { INX,      "INX"  },
    { INY,      "INY"  },
    { ASL,      "ASL"  },
    { ROL,      "ROL"  },
    { LSR,      "LSR"  },
    { ROR,      "ROR"  },
    { LDA,      "LDA"  },
    { STA,      "STA"  },
    { LDX,      "LDX"  },
    { STX,      "STX"  },
    { LDY,      "LDY"  },
    { STY,      "STY"  },
    { RMB0,     "RMB0" },
    { RMB1,     "RMB1" },
    { RMB2,     "RMB2" },
    { RMB3,     "RMB3" },
    { RMB4,     "RMB4" },
    { RMB5,     "RMB5" },
    { RMB6,     "RMB6" },
    { RMB7,     "RMB7" },
    { SMB0,     "SMB0" },
    { SMB1,     "SMB1" },
    { SMB2,     "SMB2" },
    { SMB3,     "SMB3" },
    { SMB4,     "SMB4" },
    { SMB5,     "SMB5" },
    { SMB6,     "SMB6" },
    { SMB7,     "SMB7" },
    { STZ,      "STZ" },
    { TAX,      "TAX" },
    { TXA,      "TXA" },
    { TAY,      "TAY" },
    { TYA,      "TYA" },
    { TSX,      "TSX" },
    { TXS,      "TXS" },
    { PLA,      "PLA" },
    { PHA,      "PHA" },
    { PLP,      "PLP" },
    { PHP,      "PHP" },
    { PHX,      "PHX" },
    { PHY,      "PHY" },
    { PLX,      "PLX" },
    { PLY,      "PLY" },
    { BRA,      "BRA" },
    { BPL,      "BPL" },
    { BMI,      "BMI" },
    { BVC,      "BVC" },
    { BVS,      "BVS" },
    { BCC,      "BCC" },
    { BCS,      "BCS" },
    { BNE,      "BNE" },
    { BEQ,      "BEQ" },
    { BBR0,     "BBR0" },
    { BBR1,     "BBR1" },
    { BBR2,     "BBR2" },
    { BBR3,     "BBR3" },
    { BBR4,     "BBR4" },
    { BBR5,     "BBR5" },
    { BBR6,     "BBR6" },
    { BBR7,     "BBR7" },
    { BBS0,     "BBS0" },
    { BBS1,     "BBS1" },
    { BBS2,     "BBS2" },
    { BBS3,     "BBS3" },
    { BBS4,     "BBS4" },
    { BBS5,     "BBS5" },
    { BBS6,     "BBS6" },
    { BBS7,     "BBS7" },
    { STP,      "STP" },
    { WAI,      "WAI" },
    { BRK,      "BRK" },
    { RTI,      "RTI" },
    { JSR,      "JSR" },
    { RTS,      "RTS" },
    { JMP,      "JMP" },
    { BIT,      "BIT" },
    { TRB,      "TRB" },
    { TSB,      "TSB" },
    { CLC,      "CLC" },
    { SEC,      "SEC" },
    { CLD,      "CLD" },
    { SED,      "SED" },
    { CLI,      "CLI" },
    { SEI,      "SEI" },
    { CLV,      "CLV" },
    { NOP,      "NOP" },
    { SLO,      "SLO" },
    { RLA,      "RLA" },
    { SRE,      "SRE" },
    { RRA,      "RRA" },
    { SAX,      "SAX" },
    { LAX,      "LAX" },
    { DCP,      "DCP" },
    { ISC,      "ISC" },
    { ANC,      "ANC" },
    { ANC2,     "ANC2" },
    { ALR,      "ALR" },
    { ARR,      "ARR" },
    { XAA,      "XAA" },
    { AXS,      "AXS" },
    { USBC,     "USBC" },
    { AHX,      "AHX" },
    { SHY,      "SHY" },
    { SHX,      "SHX" },
    { TAS,      "TAS" },
    { LAS,      "LAS" },

    { PRINT_ON,         "print_on" },
    { PRINT_OFF,        "print_off" },
    { IFDEF_DIR,        "ifdef" },
    { IFNDEF_DIR,       "ifndef" },
    { IF_DIR,           "if" },
    { ELSE_DIR,         "else" },
    { ENDIF_DIR,        "endif" },
    { VAR_DIR,          "var" },
    { DO_DIR,           "do" },
    { WHILE_DIR,        "while" },
    { WEND_DIR,         "wend" },
    { DS,               "defineStorage" },
    { LT,               "lessthan" },
    { GT,               "greaterthan" },
    { LE,               "lessthanequal" },
    { GE,               "greaterthanequal" },
    { DEQUAL,           "doubleequals" },
    { NOTEQUAL,         "notequal" },
    { FILL_DIR,         "FILL_DIR" },
};
